name: mcontrerasfoto
favicon: null
layout_spectrum: 0.15841490519233048
typography_spectrum: 0.5848775380291045
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.36243020417168736
  lightness: 0.7872183499857783
  saturation: 0.9024317138828337
  rhythmicContrast: 0.14094557310454547
purpose: []
