name: mcontrerasfoto
favicon: null
layout_spectrum: 0.15841490519233048
typography_spectrum: 0.5848775380291045
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#383838'
    - '#b7b7b7'
    - '#626262'
  brandStrength: 0.25
  lightness: 0.7872183499857783
  saturation: 0.9024317138828337
  rhythmicContrast: 0.5
purpose: []
